apiVersion: v1
kind: Pod
metadata:
  name: spring-pod
  labels:
    app: spring
spec:
  containers:
    - name: spring-container
      image: spring-server:latest  # Updated to match script
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1"
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  type: NodePort
  selector:
    app: spring
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080